fix: Add Start Time for todo structure.
x-start-up/Life-Copilot-Server pull request #1
Opened 2023-09-12 09:20 UTC by lbr77

2023-09-12 09:23 UTC, lyleshaw requested changes
记得执行
```
hz update -idl idl/main.thrift
```

2023-09-12 09:23 UTC, lyleshaw commented on idl/main.thrift
> +  5: string start_time
5: start_time,

需要有","

2023-09-12 09:32 UTC, lbr77 commented on idl/main.thrift
> +  5: string start_time
抱歉...我写的太急了...
晚上回来后再提交Orz

2023-09-13 03:04 UTC, lyleshaw approved these changes
LGTM

2023-09-13 03:04 UTC, merged